# (c) 2017 DataNexus Inc.  All Rights Reserved
---
# if we're provisioning a RHEL machine, then we need to ensure that
# it's subscribed before we can install anything (if it hasn't been
# registered already, of course, if that's the case then we can skip
# this step)
- block:
  - redhat_subscription:
      state: present
      username: "{{rhel_username}}"
      password: "{{rhel_password}}"
      consumer_id: "{{rhel_consumer_id}}"
    become: true
    when: rhel_username is defined and rhel_password is defined and rhel_consumer_id is defined
  when: ansible_distribution == 'RedHat'
# Now that we have all of the facts we need, we can run the roles that are used to
# deploy and configure the application we're deploying on our input nodes
- include_role:
    name: get-iface-addr
  vars:
    iface_name: "{{data_iface}}"
    as_fact: "data_addr"
  when: (data_iface | default('')) != ''
- include_role:
    name: get-iface-addr
  vars:
    iface_name: "{{api_iface}}"
    as_fact: "api_addr"
  when: (api_iface | default('')) != ''
- include_role:
    name: setup-web-proxy
  when: (proxy_env | default({})) != {}
- include_role:
    name: add-local-repository
  vars:
    yum_repository: "{{yum_repo_url}}"
  when: (yum_repo_url | default('')) != ''
- include_role:
    name: install-packages
  vars:
    package_list: "{{combined_package_list}}"
- include_role:
    name: "dn-{{application}}"
